# -*- python -*-
##
## SConscript  -  SCons buildscript for experiments and investigations.
##                Things defined here usuall won't be installed
##

Import('env core support_lib')



envR = env.Clone()
envR.Append(CPPPATH='research')
# envR.Append(CCFLAGS=' -O3 ')

# build additional test and administrative tools....
experiments = [ envR.Program('try', ['try.cpp'] + support_lib)          #### to try out some feature...
              , envR.Program('clang-static-init', ['clang-static-init-1.cpp', 'clang-static-init-2.cpp'])  
              ]

#
# define Phony targets
#  - 'scons research' triggers building of experimental code
#
env.Alias('research', experiments )
