/*
  DOMAIN.hpp  -  represent the value domain of parameters

   Copyright (C)
     2026             Hermann Vosseler <Ichthyostega@web.de>

  **Lumiera** is free software; you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by the
  Free Software Foundation; either version 2 of the License, or (at your
  option) any later version. See the file COPYING for further details.

*/


/** @file domain.hpp
 ** Specification of a base type and a value domain for parameters.
 ** A Domain descriptor implicitly also encodes the concrete value type
 ** and exposes a set of virtual functions to handle all supported value conversions.
 ** Implementing this interface creates a conversion matrix and allows to implement
 ** generic conversions by double-dispatch. Since virtual interfaces must be complete
 ** at compile time however, such an approach requires to define a finite set of
 ** supported parameter value types, which seems adequate, since the universe
 ** of possible values is limited anyway: elementary values in parameters
 ** must be primitive base types that can be created and destroyed
 ** without side effect. Relying on the further features of
 ** the parameter type system, compound types (vectors)
 ** and limited sub-scales can be defined.
 ** 
 ** @todo WIP-WIP-WIP this is a draft and placeholder, as of 2026
 */


#ifndef LIB_PAR_DOMAIN_H
#define LIB_PAR_DOMAIN_H


#include "lib/meta/typelist.hpp"
//#include "lib/meta/typelist-util.hpp"
#include "lib/meta/generator.hpp"
#include "lib/meta/trait.hpp"
#include "lib/util.hpp"

#include <concepts>
#include <limits>


namespace lib {
namespace par {
  
  using util::isNeg;
  using std::same_as;
  using std::floating_point;
  using std::numeric_limits;
  
  
  struct ValBuff { /*placeholder*/ };
  
  template<typename X>
  constexpr inline ValBuff&
  asValBuff (X& something)
  {
    void* rawMem{& something};
    return * static_cast<ValBuff*> (rawMem);
  }
  
  template<typename X>
  constexpr inline ValBuff const&
  asValBuff (X const& something)
  {
    void const * rawMem{& something};
    return * static_cast<ValBuff const *> (rawMem);
  }
  
  template<typename X>
  constexpr inline X&
  asValue (ValBuff& storage)
  {
    void* rawMem{& storage};
    return * static_cast<X*> (rawMem);
  }
  
  template<typename X>
  constexpr inline X const&
  asValue (ValBuff const& storage)
  {
    void const * rawMem{& storage};
    return * static_cast<X const *> (rawMem);
  }
  
  
  template<typename X>
  class TypeHandler
    {
      public:
        virtual void conformInto (ValBuff&, X const&)   =0;
    };
  
//  using lib::meta::typeseq;
  
  
  using BaseTypes = meta::Types<int
                               ,int64_t
                               ,uint
                               ,uint64_t
                               ,double
                               ,float
                               ,bool
                               >;
  /** build a generic visitor interface for all types in list */
  using TypeHandlerInterface = meta::InstantiateForEach<BaseTypes::List, TypeHandler>;
  
  
  /**
   * Interface: mark the allowed value domain of a parameter value.
   * The identity of the actual implementation can be used as type descriptor,
   * since all concrete full base domains are registered at compile time; the
   * virtual Domain interface exposes the possible conversions.
   * @todo 7/2026 not clear if we can support all conversions unconditionally,
   *       or if some notion of an _impossible conversion_ is required. It is
   *       clear however, that the access to an actual parameter **must fail**
   *       at compile time, if a sensible conversion can not be provided.
   */
  class Domain
    : public TypeHandlerInterface
    {
    public:
      virtual ~Domain();  ///< this is an interface
      
      virtual void applyLimit (ValBuff&)  =0;
      virtual void supply(ValBuff const& src, ValBuff& target, Domain& targetDomain) =0;
      
      template<typename X>
      void extractAs (X& targetVal, ValBuff const& valBuff);
      
      template<typename X>
      void conform (ValBuff& targetBuff, X&& srcVal);
      
    protected:
    };
  
  
  
// GCC > 13 warns at class definition when a new overload shadows an inherited virtual function.
// While theoretically correct, in practice any call will be dispatched through the base interface,
// which in turn is also generated by metaprogramming from a type list.
// See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109740
_Pragma("GCC diagnostic push") \
_Pragma("GCC diagnostic ignored \"-Woverloaded-virtual\"")
  
  
  
  template<typename V>
  struct DomainSetup
    {
      
      template<typename X, class BAS>
      class TypeHandlerImpl
        : public BAS
        {
          void conformInto (ValBuff& targetBuff, X const& srcVal)  override;
        };
      
      using TypeHandlerChain = meta::InstantiateChained<BaseTypes::List, TypeHandlerImpl, Domain>;
    };
  
  
  
  template<typename V>
  class BaseDomain
    : public DomainSetup<V>::TypeHandlerChain
    {
    public:
      void applyLimit (ValBuff&)  override;
      void supply (ValBuff const& src, ValBuff& target, Domain& targetDomain)  override;
    };
  
  
  /* ===== type conversion details ===== */
  
  /** Constraint: type \a SUB can not represent the full domain of type \a BAS
   * @todo implicitly also implements a limitation to »numeric« types,
   *       due to the use of std::numeric_limits
   */
  template<typename SUB, typename BAS>
  concept sub_domain = std::signed_integral<SUB> != std::signed_integral<BAS>
                    or std::numeric_limits<SUB>::max() < std::numeric_limits<BAS>::max()
                    or std::numeric_limits<SUB>::lowest() > std::numeric_limits<BAS>::lowest()
                     ;
  
  
_Pragma("GCC diagnostic push") \
_Pragma("GCC diagnostic ignored \"-Wsign-compare\"")
// the following functions are specifically crafted to work around
// the ambiguities caused by automatic signed-to-unsigned promotion;
// furthermore, the automatic promotion allows to perform the comparison.
  
  template<typename X, typename Y>
  inline constexpr bool
  isLower_safe (X const& x, Y const& y)
  {
    return isNeg(x) == isNeg(y)? x < y
                               : isNeg(x);
  }

  template<typename X, typename Y>
  inline constexpr bool
  isLarger_safe (X const& x, Y const& y)
  {
    return isNeg(x) == isNeg(y)? x > y
                               : isNeg(y);
  }
_Pragma("GCC diagnostic pop")
  
  /** generic helper to conform into a common value domain
   * @tparam SUB the implied target value domain
   * @tparam BAS source data type
   * @return a value in source data type,
   *         yet conformed into the target data range
   */
  template<typename SUB, typename BAS>
  inline constexpr BAS
  preClamp (BAS const& value)
  {
    return value;
  }
  
  /** special case: clamp the source value into the target value domain.
   * @remark tricky due to automatic conversions between signed/unsigned */
  template<typename SUB, typename BAS>   requires (sub_domain<SUB,BAS>
                                                   and not same_as<SUB,bool>)
  inline constexpr BAS
  preClamp (BAS const& rawVal)
  {
    static_assert (std::is_constructible_v<BAS,SUB const&>
                  ,"Value domains must overlap at least partially "
                   "and values must be cross-constructible within overlap");
    
    auto upperBound = numeric_limits<SUB>::max();
    auto lowerBound = numeric_limits<SUB>::lowest();
    
    return isLarger_safe(rawVal, upperBound)? BAS(upperBound)
         : isLower_safe (rawVal, lowerBound)? BAS(lowerBound)
                                            : rawVal;
  }
  
  /** special case: trigger a bool at the 0.5 level */
  template<same_as<bool> B, floating_point F>
  inline constexpr F
  preClamp (F const& rawVal)
  {
    return 0.5 < rawVal? F{1} : F{0};
  }
  
  
  
  template<typename V>
  inline void
  BaseDomain<V>::applyLimit (ValBuff& valBuff)
  {
    V& val{asValue<V> (valBuff)};
    val = preClamp<V> (val);
  }
  
  
  template<typename V, typename X>
  inline void
  assignConverted (V& targetVal, X const& srcVal)
  {
    if constexpr (std::is_assignable_v<V&, X const&>)
      {
        targetVal = preClamp<V> (srcVal);
      }
    else
    if constexpr (std::is_constructible_v<V, X const&>)
      {
        targetVal.~U();
        new(&targetVal) V (preClamp<V> (srcVal));
      }
    else
      static_assert (!sizeof(X), "this type conversion is not supported");
  }
  
  
  template<typename V>
  template<typename X, class BAS>
  inline void
  DomainSetup<V>::TypeHandlerImpl<X,BAS>::conformInto (ValBuff& targetBuff, X const& srcVal)
  {
    V& targetVal = asValue<V> (targetBuff);
    assignConverted (targetVal, srcVal);
  }
  

  template<typename V>
  inline void
  BaseDomain<V>::supply (ValBuff const& srcBuff, ValBuff& targetBuff, Domain& targetDomain)
  {
    targetDomain.conform (targetBuff, asValue<V> (srcBuff));
  }
  
  template<typename X>
  inline void
  Domain::extractAs (X& targetVal, ValBuff const& valBuff)
  {
    BaseDomain<X> target;
    ValBuff& targetBuff{asValBuff<X> (targetVal)};
    supply (valBuff, targetBuff, target);
  }
  
  template<typename X>
  inline void
  Domain::conform (ValBuff& targetBuff, X&& srcVal)
  {
    using Src = std::decay_t<X>;
    TypeHandler<Src>& typeHandler{*this};
    typeHandler.conformInto (targetBuff, srcVal);
    applyLimit (targetBuff);
  }
  
  
  
  
}} // namespace lib::par
#endif /*LIB_PAR_DOMAIN_H*/
