/*
  PARAM-TYPE.hpp  -  parameter type record including domain and scale

   Copyright (C)
     2026             Hermann Vosseler <Ichthyostega@web.de>

  **Lumiera** is free software; you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by the
  Free Software Foundation; either version 2 of the License, or (at your
  option) any later version. See the file COPYING for further details.

*/


/** @file param-type.hpp
 ** Specification of the value domain and scale of a parameter.
 ** The implementation of parameters is built up in layers, starting from the generic
 ** interfaces \ref Provision, which describes the fundamental capabilities of a
 ** parameter as conceptualised here) and \ref Domain to support type conversions.
 ** 
 ** All extensions beyond this point can be considered implementation-level services.
 ** The BaseDomain layer provides the actual type conversion services, based on internal
 ** knowledge of the concrete data type handled by this parameter.
 ** 
 ** A \ref TypedEntity descriptor adds storage to capture type properties and allow
 ** for an ID registration. In addition, the concrete value type is tagged, marking
 ** the allowed value range, clipping behaviour and specifics of the scale (discrete,
 ** stepping, continuous, logarithmic...).
 ** 
 ** @todo WIP-WIP-WIP can be considered an initial draft and placeholder, as of 2026
 */


#ifndef LIB_PAR_PARAM_TYPE_H
#define LIB_PAR_PARAM_TYPE_H


#include "lib/par/domain.hpp"
#include "lib/par/type-handler.hpp"
#include "lib/meta/generator.hpp"


namespace lib {
namespace par {
  
// GCC > 13 warns at class definition when a new overload shadows an inherited virtual function.
// While theoretically correct, in practice any call will be dispatched through the base interface,
// which in turn is also generated by metaprogramming from a type list.
// See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109740
_Pragma("GCC diagnostic push") \
_Pragma("GCC diagnostic ignored \"-Woverloaded-virtual\"")
  
  
  template<typename VAL, class IFA>
  struct DomainSetup
    {
      
      template<typename X, class PAR>
      class TypeHandlerImpl
        : public PAR
        {
          void extractAs (X& targetVal, ValBuff const& valBuff) const override;
          void conform (ValBuff& targetBuff, X const& srcVal)         override;
        };
      
      using TypeHandlerChain = meta::InstantiateChained<BaseTypes::List, TypeHandlerImpl, IFA>;
    };
  
  
  
  template<typename VAL, class IFA>
  class BaseDomain
    : public DomainSetup<VAL, IFA>::TypeHandlerChain
    {
    public:
      void applyLimit (ValBuff&)  override;
      void transferTo (ValBuff const& source, Domain& targetDomain, ValBuff& target)  const override;
    };
  
  
  
  
  
  /* ===== type conversion virtual dispatch ===== */
  
  template<typename VAL, class IFA>
  template<typename X, class PAR>
  inline void
  DomainSetup<VAL,IFA>::TypeHandlerImpl<X,PAR>::extractAs (X& targetVal, ValBuff const& valBuff)  const
  {
    VAL const& srcVal = asValue<VAL> (valBuff);
    assignConverted (targetVal, srcVal);
  }
  
  
  template<typename VAL, class IFA>
  template<typename X, class PAR>
  inline void
  DomainSetup<VAL,IFA>::TypeHandlerImpl<X,PAR>::conform (ValBuff& targetBuff, X const& srcVal)
  {
    VAL& targetVal = asValue<VAL> (targetBuff);
    assignConverted (targetVal, srcVal);
  }
  

  template<typename VAL, class IFA>
  inline void
  BaseDomain<VAL,IFA>::applyLimit (ValBuff& valBuff)
  {
    VAL& val{asValue<VAL> (valBuff)};
    val = preClamp<VAL> (val);
  }
  
  
  template<typename VAL, class IFA>
  inline void
  BaseDomain<VAL,IFA>::transferTo (ValBuff const& source, Domain& targetDomain, ValBuff& target)  const
  {
    targetDomain.conform (target, asValue<VAL> (source));
    targetDomain.applyLimit (target);
  }
  
  
  
  
  
  /**
   * Service-Interface: represent a specific configuration of parameter value type,
   * range and scale. Every ParamType descriptor is also a _prototype_ and has
   * an unique identity, ensured by registration, so that it acts as a type identifier.
   * @todo RLY? registration??
   * Furthermore, the interface exposes allowed conversion and conforming operations.
   */
  template<typename VAL, class IFA>
  class TypedEntity
    : public BaseDomain<VAL,IFA>
    {
    public:
    };
  
  
  
}} // namespace lib::par
#endif /*LIB_PAR_PARAM_TYPE_H*/
