/*
  PROP-BUILDER.hpp  -  generate data record with arbitrary named fields

   Copyright (C)
     2026,            Hermann Vosseler <Ichthyostega@web.de>

  **Lumiera** is free software; you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by the
  Free Software Foundation; either version 2 of the License, or (at your
  option) any later version. See the file COPYING for further details.

*/


/** @file prop-builder.hpp
 ** A builder for compile-time generation of data records with arbitrary named fields.
 ** Generally speaking, a "record" in this context means just a struct or class with some
 ** data fields, and can be easily defined to suit any needs. However, such a class definition
 ** always incurs some _syntactical overhead_ — which is fine for spelling out some type in
 ** general, but can be problematic when the data record is only used once, locally and
 ** is without further significance beyond that single usage. Such a situation often
 ** arises in the context of _policy based design_ and flexible configuration of
 ** some generic facility, especially when part of this configuration involves
 ** the definition of _callback functions._
 ** 
 ** A common requirement that lends itself well to policy based design arises when such callbacks
 ** establish a deeply interwoven link into local implementation details; this kind of interconnected
 ** implementation can be expressed succinctly through Lambda functions with contextual capture, and
 ** allows to setup a tight interconnection between implementation back-ends, without exposing any
 ** of these implementation details at the interface / dependency-injection level. However, the task
 ** to package several such specific callbacks into a policy instance and pass this configured policy
 ** for creation of service instances, can be surprisingly complex, verbose, confusing and leads
 ** to code that is hard to maintain. The reasons for this challenge are manifold:
 ** - contextual capture works only well from directly within an implementation function
 ** - such a setup can not be expressed well through types and interfaces, since the
 **   generated closure is _essentially a value_ and its type can not be spelled out.
 ** - a policy with several callbacks thus turns into a template with several type parameters,
 **   and must be initialised through a likewise template based constructor; the resulting code
 **   tends to become very technical, verbose, surprisingly tricky and hard to decipher for
 **   any reader not familiar with all the intricate details of the implementation.
 ** 
 ** The root of these difficulties of proper formulation seems to be related to the nature
 ** of cohesive, closely interwoven implementation code. As long as this kind of structure
 ** can be kept close together, it works surprisingly well and expresses intent clearly.
 ** Yet as soon as it must be taken apart, expressed in names, types and interfaces,
 ** a high conceptual burden is added, which leads to the danger of generalisation
 ** and re-use beyond the very specific case, to which the original formulation
 ** of the problem was well adapted and adequate.
 ** 
 ** The solution promoted here thus aims to remove the need to define any type and interface
 ** explicitly; a builder-expression is created rather, which allows to bind all callbacks
 ** and further parameters directly inline, within a single constructor invocation.
 ** Such a setup becomes possibly through a combination of some C++20 features, linked
 ** together by lambda expressions generated from a _macro_.
 ** - the PropBuilder acts as base class for the generated records, and is used to
 **   initiate the build-up of the definition expression.
 ** - several »layers« of derived classes are added step by step, where each such
 **   layer adds one further _property_ attribute, that is initialised by a given value.
 ** - the _junctor_ to combine those layer is provided by the template function
 **   `PropBuilder::define(builder-λ, value)`. It uses the new _explicit object_
 **   syntax introduced with C++20, to pick up the "self type" as template argument.
 ** - by invoking this builder function, the current "this"-object is _moved_ into
 **   the builder, where it is used to create and initialise a derived class.
 ** - for each »layer« a specific lambda is generated by a macro — and it is this
 **   technique that allows to accept a lexical token form the program text and
 **   use this token as field name in the next derived class to generate.
 ** @see PropBuilder_test for detailed explanation
 ** @see OutputProxyProvider_test for a usage example
 */


#ifndef LIB_META_PROP_BUILDER_H
#define LIB_META_PROP_BUILDER_H


#include "lib/meta/trait.hpp"

#include <utility>


namespace lib {
namespace meta{
  
  using std::move;
  using std::forward;
  
  
  /**
   * Anchor record and builder mechanics for generating data records.
   * - start a builder expression by constructing an anonymous `PropBulder()`
   * - invoke PropBuilder::define() for each further property to add
   * - pass a builder-λ as first argument, and the data value as second
   * - generate a suitable builder-λ with the macro `PROP_FIELD(fieldname)`
   * - overall, the builder expression generates a RValue, that will usually
   *   be passed directly to the constructor of another class.
   * @see PropBuilder_test::simpleUsage
   */
  struct PropBuilder
    {
      /**
       * Core builder operation: invoke a builder-λ to extend »this«
       * @param layerBuilder a specially crafted invokable, that takes _this object_
       *   and the given property value and creates an instance of a derived class.
       * @note the macro \ref PROP_FIELD below will generate a suitable argument.
       * @param val an arbitrary (movable) data element to be stored as property.
       * @remark C++20 introduced the syntax for _explicit object member functions_,
       *   which allow to bind the "self" object instance to an explicitly defined
       *   first function parameter. Since this builder operation will be invoked
       *   on the generated compound object, the template parameter \a BAS will
       *   denote this compound, and the next builder-λ will derive from it.
       */
      template<class BAS, class LAY, typename VAL>
      auto
      define (this BAS&& chain, LAY const& layerBuilder, VAL&& val)
        {
          return layerBuilder (move(chain), forward<VAL>(val));
        }
    };
  
  
#define PROP_FIELD(FIELD_NAME)        \
  []<class BAS, typename VAL>          \
    (BAS&& bas, VAL&& val)              \
    {                                    \
      using BaseLayer = std::decay_t<BAS>;\
      using Property  = std::decay_t<VAL>; \
                                            \
        struct DataLayer_ ## FIELD_NAME      \
          : BaseLayer                         \
          {                                    \
            Property FIELD_NAME;                \
                                                 \
            DataLayer_ ## FIELD_NAME (BaseLayer b \
                                     ,Property v)  \
              : BaseLayer{move(b)}                  \
              ,FIELD_NAME{move(v)}                   \
              { }                                     \
          };                                           \
      return DataLayer_ ## FIELD_NAME {forward<BAS>(bas)\
                                      ,forward<VAL>(val) \
                                      };                  \
    }
  
  
  
}} // namespace lib::meta
#endif /*LIB_META_PROP_BUILDER_H*/
