# -*- python -*-
##
## SConscript  -  SCons buildscript for Documentation
##


Import('env')


#doxydoc = env.Doxygen('devel/Doxyfile')

#  env.Install(dir = '$DESTDIR/share/doc/lumiera$VERSION/devel', source=documentation)
#env.Clean (doxydoc, doxydoc + ['devel/,doxylog','devel/warnings.txt'])


#Export('doxydoc')
