# -*- python -*-
##
## SConscript  -  SCons buildscript for Documentation
##


Import('env')


doxydoc = env.Doxygen('devel/Doxyfile')
env.Clean(doxydoc, doxydoc + ['devel/,doxylog','devel/doxygen-warnings.txt'])

# HTML-documentation: this is a *placeholder* (eventually we'll build a user manual via Asciidoc)
env.DocFile('devel', 'LumieraHelpLandingPage.html', 'manual-html/index.html')


Export('doxydoc')
