# -*- python -*-
##
## SConscript  -  SCons buildscript for tool subdirectory (called by SConstruct)
##

Import('env','artifacts','core')


# build the ubiquitous Hello World application (note: C source)
artifacts['tools'] = [ env.Program('#$BINDIR/hello-world','hello.c')
                     + env.Program('#$BINDIR/luidgen', ['luidgen.c']+core)
                     + env.Program('#$BINDIR/try', 'try.cpp')             #### to try out some feature...
                     ]

