# -*- python -*-
##
## SConscript  -  SCons buildscript for tool subdirectory (called by SConstruct)
##

Import('env','artifacts','core')

support_lib = artifacts['support']

envSvg = env.Clone()
envSvg.mergeConf(['librsvg-2.0','gthread-2.0'])
envSvg.Append(LIBS=support_lib)


vgsuppr = env.Program('#$BINDIR/vgsuppression','vgsuppression.c', LIBS=core)## for suppressing false valgrind alarms
luidgen =    env.Program('#$BINDIR/luidgen', 'luidgen.c', LIBS=support_lib) ## for generating Lumiera-UIDs
rsvg    = envSvg.Program('#$BINDIR/rsvg-convert','rsvg-convert.c')          ## for rendering SVG icons (uses librsvg) 

# build additional test and administrative tools....
artifacts['tools'] = [ env.Program('#$BINDIR/hello-world','hello.c')      #### hello world (checks C build)      
                     + env.Program('#$BINDIR/try', 'try.cpp')             #### to try out some feature...
#                    + luidgen
                     + vgsuppr
                     + rsvg
                     ]

# Rendering the SVG Icons depends on rsvg-convert
env.Depends(artifacts['icons'], rsvg)

