.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LUMIERA 1 "January 11, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
Lumiera \- professional video/film editor for Linux
.SH SYNOPSIS
.B lumiera
.RI [ options ] " session-file" ...
.br
.B TODO_special_helpers
.SH DESCRIPTION
This manual page documents the the
.B lumiera
and
.B TODO_foobar
commands.
.PP
.B Lumiera
is an full featured professional video/film editing and compositing tool.
The application will typically be used interactively; but it is also possible
to use some subsystems in a "headless" script-driven fashion.
.PP
.B NOTE: "as of 2/2011, Lumiera is in early development and not usable in any way."
This package is a preview version intended for Lumiera developers only.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Users Manual.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.SH SEE ALSO
.BR foo (1),
.BR bar (1).
.br
The Lumiera application will be documented fully by
.IR "Lumiera Users Manual" ,
which will hopefully be written eventually.....
.SH AUTHOR
Lumiera is currently been developed by Joel Holdsworth, Christian Thäter,
Hermann Voßeler (aka Ichthyostega) and other members of the Lumiera.org team.
.PP
This manual page was added by Ichthyostega <deb@ichthyostega.de>,
for the Debian project (but may be used by others).

