Document: lumiera
Title: Debian lumiera Manual
Author: <insert document author here>
Abstract: This manual describes what lumiera is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lumiera/lumiera.sgml.gz

Format: postscript
Files: /usr/share/doc/lumiera/lumiera.ps.gz

Format: text
Files: /usr/share/doc/lumiera/lumiera.text.gz

Format: HTML
Index: /usr/share/doc/lumiera/html/index.html
Files: /usr/share/doc/lumiera/html/*.html


