#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, make this file executable.

# see wiki/index.html#GitNotes%20GitAliases for information

git sign "$(git-symbolic-ref HEAD | cut -d/ -f 3-)_signature"
git publish

